language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t kumard31/react-test -f ./client/Dockerfile.dev
script:
  - docker run -e CI=true kumard31/react-test npm test   
after_success:
  - docker build -t kumard31/multi-client -f ./client 
  - docker build -t kumard31/multi-nginx -f ./nginx
  - docker build -t kumard31/multi-worker -f ./worker
  - docker build -t kumard31/multi-server -f ./server
#Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
#Docker images push
  - docker push kumard31/multi-client
  - docker push kumard31/multi-nginx
  - docker push kumard31/multi-worker
  - docker push kumard31/multi-server

notification:
  email:
    - ee_deepakkumar@rediffmail.com
